[project]
name = "cred-next-back-end"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Veeranki Jitendra", email = "jitendra@ratnamsolutions.com" }
]
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.20.0",
    "bcrypt>=5.0.0",
    "email-validator>=2.3.0",
    "fastapi>=0.141.1",
    "passlib>=1.7.4",
    "psycopg[binary]>=3.3.6",
    "pydantic-settings>=2.15.0",
    "sqlalchemy>=2.0.54",
    "uvicorn[standard]>=0.53.0",
]

[project.scripts]
cred-next-back-end = "cred_next_back_end:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
