"""create lead table

Revision ID: 7b6360ecf1e5
Revises: 1c2c980dfb78
Create Date: 2026-10-03 11:35:36.630864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b6360ecf1e5'
down_revision: Union[str, Sequence[str], None] = '1c2c980dfb78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('lead_id', sa.String(length=45), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('referred_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('application_type', sa.String(length=100), nullable=False),
    sa.Column('loan_type', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('contact_number', sa.String(length=10), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('loan_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('monthly_income', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referred_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_id')
    )
    op.create_index(op.f('ix_leads_contact_number'), 'leads', ['contact_number'], unique=False)
    op.create_index(op.f('ix_leads_created_by_user_id'), 'leads', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_leads_referred_by_user_id'), 'leads', ['referred_by_user_id'], unique=False)
    op.drop_constraint(op.f('otp_verification_user_id_fkey'), 'otp_verification', type_='foreignkey')
    op.create_foreign_key(None, 'otp_verification', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'otp_verification', type_='foreignkey')
    op.create_foreign_key(op.f('otp_verification_user_id_fkey'), 'otp_verification', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_leads_referred_by_user_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_created_by_user_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_contact_number'), table_name='leads')
    op.drop_table('leads')
    # ### end Alembic commands ###
