"""replace refresh token with hash

Revision ID: ed5ca1365e15
Revises: 6158b1253842
Create Date: 2026-09-24 18:23:03.929319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed5ca1365e15'
down_revision: Union[str, Sequence[str], None] = '6158b1253842'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token_hash', sa.String(length=300), nullable=True))
    op.drop_column('users', 'refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.drop_column('users', 'refresh_token_hash')
    # ### end Alembic commands ###
